# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-04-28 21:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='media',
            field=models.FileField(default=datetime.datetime(2016, 4, 28, 21, 26, 59, 67090, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
